export const AUDIT_ACTIONS = {
  // Authentication
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  // Sessions
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_REVOKED: "SESSION_REVOKED",
  ALL_SESSIONS_REVOKED: "ALL_SESSIONS_REVOKED",

  // Users
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ROLE_UPDATED: "USER_ROLE_UPDATED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",

  // Employee
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_DELETED: "EMPLOYEE_DELETED",
  EMPLOYEE_DOCUMENT_UPDATED: "EMPLOYEE_DOCUMENT_UPDATED",
  EMPLOYEE_SALARY_UPDATED: "EMPLOYEE_SALARY_UPDATED",

  // Branches
  BRANCH_CREATED: "BRANCH_CREATED",
  BRANCH_UPDATED: "BRANCH_UPDATED",
  BRANCH_ACTIVATED: "BRANCH_ACTIVATED",
  BRANCH_DEACTIVATED: "BRANCH_DEACTIVATED",

  // Holiday
  HOLIDAY_CREATED: "HOLIDAY_CREATED",
  HOLIDAY_UPDATED: "HOLIDAY_UPDATED",
  HOLIDAY_DELETED: "HOLIDAY_DELETED",

  // Security
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",

  // Leads
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_DELETED: "LEAD_DELETED",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  LEAD_REASSIGNED: "LEAD_REASSIGNED",
  LEAD_STATUS_UPDATED: "LEAD_STATUS_UPDATED",
  LEAD_REMARK_ADDED: "LEAD_REMARK_ADDED",
  LEADS_IMPORTED: "LEADS_IMPORTED",
  BULK_LEADS_ASSIGNED: "BULK_LEADS_ASSIGNED",

  // Dialer
  CALL_INITIATED: "CALL_INITIATED",
  CALL_COMPLETED: "CALL_COMPLETED",
  CALL_RECORDING_ACCESSED: "CALL_RECORDING_ACCESSED",

  // Tasks
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_STATUS_UPDATED: "TASK_STATUS_UPDATED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
