import { ROLES, type Role } from "../constants/roles.js";
import {
  PERMISSIONS,
  type Permission,
} from "../constants/permissions.js";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  // =========================================================
  // HEAD
  // =========================================================

  [ROLES.HEAD]: Object.values(PERMISSIONS),

  // =========================================================
  // ADMIN
  // =========================================================

  [ROLES.ADMIN]: [
    // Users
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.USER_ASSIGN_BRANCH,
    PERMISSIONS.USER_STATUS_UPDATE,

    // Branches
    PERMISSIONS.BRANCH_VIEW,

    // Lead Sources
    PERMISSIONS.LEAD_SOURCE_READ,
    PERMISSIONS.LEAD_SOURCE_CREATE,
    PERMISSIONS.LEAD_SOURCE_UPDATE,

    // Leads
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_REASSIGN,
    PERMISSIONS.LEAD_IMPORT,
    PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.LEAD_BULK_UPDATE,
    PERMISSIONS.LEAD_BULK_ASSIGN,

    // Lead activities
    PERMISSIONS.LEAD_ACTIVITY_VIEW,
    PERMISSIONS.LEAD_ACTIVITY_CREATE,

    // Follow-ups
    PERMISSIONS.LEAD_FOLLOWUP_VIEW,
    PERMISSIONS.LEAD_FOLLOWUP_CREATE,
    PERMISSIONS.LEAD_FOLLOWUP_UPDATE,

    // Customers
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    // Tasks
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,

    // Activities
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.ACTIVITY_UPDATE,

    // Attendance
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    // Salary
    PERMISSIONS.SALARY_VIEW,

    // Achievements
    PERMISSIONS.ACHIEVEMENT_VIEW,
    PERMISSIONS.ACHIEVEMENT_CREATE,
    PERMISSIONS.ACHIEVEMENT_UPDATE,

    // Performance
    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_MANAGE,

    // Incentives
    PERMISSIONS.INCENTIVE_VIEW,
    PERMISSIONS.INCENTIVE_CREATE,
    PERMISSIONS.INCENTIVE_UPDATE,
    PERMISSIONS.INCENTIVE_MANAGE,

    // Revenue
    PERMISSIONS.REVENUE_VIEW,

    // Reports
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    // Audit
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_READ,
  ],

  // =========================================================
  // MANAGER
  // =========================================================

  [ROLES.MANAGER]: [
    // Users
    PERMISSIONS.USER_VIEW,

    // Branch
    PERMISSIONS.BRANCH_VIEW,

    // Lead Sources
    PERMISSIONS.LEAD_SOURCE_READ,

    // Leads
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_REASSIGN,

    // Lead activities
    PERMISSIONS.LEAD_ACTIVITY_VIEW,
    PERMISSIONS.LEAD_ACTIVITY_CREATE,

    // Follow-ups
    PERMISSIONS.LEAD_FOLLOWUP_VIEW,
    PERMISSIONS.LEAD_FOLLOWUP_CREATE,
    PERMISSIONS.LEAD_FOLLOWUP_UPDATE,

    // Customers
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    // Tasks
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,

    // Activities
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.ACTIVITY_UPDATE,

    // Attendance
    PERMISSIONS.ATTENDANCE_VIEW,

    // Achievements
    PERMISSIONS.ACHIEVEMENT_VIEW,
    PERMISSIONS.ACHIEVEMENT_CREATE,

    // Performance
    PERMISSIONS.PERFORMANCE_VIEW,

    // Incentives
    PERMISSIONS.INCENTIVE_VIEW,

    // Revenue
    PERMISSIONS.REVENUE_VIEW,

    // Reports
    PERMISSIONS.REPORT_VIEW,
  ],

  // =========================================================
  // EMPLOYEE
  // =========================================================

  [ROLES.EMPLOYEE]: [
    // Own / assigned users visibility
    PERMISSIONS.USER_VIEW,

    // Lead Sources
    PERMISSIONS.LEAD_SOURCE_READ,

    // Leads
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,

    // Lead activities
    PERMISSIONS.LEAD_ACTIVITY_VIEW,
    PERMISSIONS.LEAD_ACTIVITY_CREATE,

    // Follow-ups
    PERMISSIONS.LEAD_FOLLOWUP_VIEW,
    PERMISSIONS.LEAD_FOLLOWUP_CREATE,
    PERMISSIONS.LEAD_FOLLOWUP_UPDATE,

    // Customers
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    // Tasks
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,

    // Activities
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.ACTIVITY_UPDATE,

    // Attendance
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,

    // Own achievements
    PERMISSIONS.ACHIEVEMENT_VIEW,

    // Own performance
    PERMISSIONS.PERFORMANCE_VIEW,

    // Own incentives
    PERMISSIONS.INCENTIVE_VIEW,

    // Own revenue
    PERMISSIONS.REVENUE_VIEW,

    // Own reports
    PERMISSIONS.REPORT_VIEW,
  ],
};