import { ROLES, type Role } from "../constants/roles.js";
import { PERMISSIONS, type Permission } from "../constants/permissions.js";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.HEAD]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.USER_ASSIGN_BRANCH,
    PERMISSIONS.USER_STATUS_UPDATE,

    // PERMISSIONS.BRANCH_VIEW,

    PERMISSIONS.LEAD_SOURCE_CREATE,
    PERMISSIONS.LEAD_SOURCE_UPDATE,
    PERMISSIONS.LEAD_SOURCE_READ,
    PERMISSIONS.LEAD_SOURCE_DELETE,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_DELETE,
    PERMISSIONS.LEAD_ASSIGN,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_ASSIGN,

    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.ACTIVITY_UPDATE,
    PERMISSIONS.ACTIVITY_DELETE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_READ,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_ASSIGN_BRANCH,
    PERMISSIONS.USER_STATUS_UPDATE,

    // PERMISSIONS.BRANCH_VIEW,

    PERMISSIONS.LEAD_SOURCE_READ,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_ASSIGN,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,

    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.ACTIVITY_UPDATE,

    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.LEAD_SOURCE_READ,

    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,

    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
    PERMISSIONS.ACTIVITY_UPDATE,
  ],
};
